### ISSUE TITLE
组织层面使用GitHub Actions

### ISSUE THREAD

**Issue by Guo-Zhang** [quanttide/quanttide-github-actions#1]
您可以在 GitHub 组织（Organization）层面配置和使用 GitHub Actions。这样，所有属于该组织的仓库都可以使用该 Actions 工作流。

以下是在组织层面使用 GitHub Actions 的一些步骤：

1. 打开您的 GitHub 组织页面，并转到 `Settings`。

2. 在 `Settings` 页面上方的选项卡中，单击 `Actions`。

3. 在 `Actions` 页面上，启用组织级别的 Actions 功能。您可能需要阅读并接受 GitHub 的条款和条件。

4. 现在您可以在组织层面创建和管理 Actions 工作流。要创建一个新的工作流，请在组织仓库中创建一个名为 `.github/workflows` 的目录，并在其中添加一个名为 `example.yml` 的 YAML 文件。这个文件中包含您的工作流定义。

   以下是一个示例 `example.yml` 文件：

   ````yaml
   name: Example Workflow
   on:
     push:
       branches:
         - main
   jobs:
     build:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v2
         - name: Example Step
           run: echo "Hello, world!"
   ```

   这个示例工作流定义了一个名为 `build` 的作业（job），它会在 `main` 分支上的代码提交时运行。作业使用 `ubuntu-latest` 运行环境，并包含一个名为 `Example Step` 的步骤，它会输出一条简单的消息。

5. 将 `.github/workflows` 目录和 `example.yml` 文件推送到您的组织仓库中。您可以使用 Git 命令或 GitHub 网络界面上传文件。

现在，当您的组织中的任何仓库的 `main` 分支有代码提交时，GitHub Actions 将会自动运行 `example.yml` 工作流，并执行其中定义的操作。

需要注意的是，组织层面的 Actions 与仓库层面的 Actions 有所不同。组织层面的 Actions 可以访问组织的所有仓库和存储库机密（secrets），因此请确保只有受信任的人员可以管理和编辑您的工作流定义。
